layout_spectrum: 0.2389903
typography_spectrum: 0.4398496
color:
  saturation: 0.4072646
  lightness: 0.8535617
  brandStrength: 0.841503
  rhythmicContrast: 0.4587171
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Monocca
